import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { createSupabaseServerClient } from "~/lib/supabase";

export const exportSQL = createServerFn({ method: "GET" })
  .inputValidator(z.object({ projectId: z.string() }))
  .handler(async ({ data, request }) => {
    const supabase = createSupabaseServerClient(request);

    // Verify user is authenticated
    const { data: { user }, error: authError } = await supabase.auth.getUser();
    if (authError || !user) {
      throw new Error("Unauthorized");
    }

    // Get project with all tables, columns, and relationships
    const { data: project, error: projectError } = await supabase
      .from("erd_projects")
      .select("*")
      .eq("id", data.projectId)
      .single();

    if (projectError) throw projectError;

    const { data: tables, error: tablesError } = await supabase
      .from("erd_tables")
      .select(
        `
        *,
        erd_columns (*)
      `
      )
      .eq("project_id", data.projectId)
      .order("created_at", { ascending: true });

    if (tablesError) throw tablesError;

    const { data: relationships, error: relationshipsError } = await supabase
      .from("erd_relationships")
      .select("*")
      .in(
        "source_table_id",
        tables.map((t: any) => t.id)
      );

    if (relationshipsError) throw relationshipsError;

    // Generate SQL
    let sql = `-- Generated by Ember ERD Designer\n`;
    sql += `-- Project: ${project.name}\n`;
    if (project.description) {
      sql += `-- Description: ${project.description}\n`;
    }
    sql += `-- Generated at: ${new Date().toISOString()}\n\n`;

    // Create tables
    for (const table of tables) {
      sql += `CREATE TABLE ${table.name} (\n`;

      const columns = (table.erd_columns || []).sort(
        (a: any, b: any) => a.order - b.order
      );

      const columnDefs = columns.map((col: any) => {
        let def = `  ${col.name} ${col.type}`;
        if (col.is_primary) def += " PRIMARY KEY";
        if (col.is_unique && !col.is_primary) def += " UNIQUE";
        if (!col.nullable) def += " NOT NULL";
        if (col.default_value) def += ` DEFAULT ${col.default_value}`;
        return def;
      });

      sql += columnDefs.join(",\n");
      sql += `\n);\n\n`;
    }

    // Create relationships (foreign keys)
    if (relationships && relationships.length > 0) {
      sql += `-- Foreign Key Constraints\n`;

      for (const rel of relationships) {
        const sourceTable = tables.find((t: any) => t.id === rel.source_table_id);
        const targetTable = tables.find((t: any) => t.id === rel.target_table_id);

        if (!sourceTable || !targetTable) continue;

        const sourceColumn = sourceTable.erd_columns?.find(
          (c: any) => c.id === rel.source_column_id
        );
        const targetColumn = targetTable.erd_columns?.find(
          (c: any) => c.id === rel.target_column_id
        );

        if (!sourceColumn || !targetColumn) continue;

        // Determine which table has the FK based on relationship type
        // one-to-many & one-to-one: target has FK referencing source
        // many-to-one: source has FK referencing target
        let fkTable, fkColumn, refTable, refColumn;

        if (rel.type === "one-to-many" || rel.type === "one-to-one") {
          fkTable = targetTable;
          fkColumn = targetColumn;
          refTable = sourceTable;
          refColumn = sourceColumn;
        } else if (rel.type === "many-to-one") {
          fkTable = sourceTable;
          fkColumn = sourceColumn;
          refTable = targetTable;
          refColumn = targetColumn;
        } else {
          // many-to-many would need a junction table, skip for now
          continue;
        }

        sql += `ALTER TABLE ${fkTable.name}\n`;
        sql += `  ADD CONSTRAINT fk_${fkTable.name}_${refTable.name}\n`;
        sql += `  FOREIGN KEY (${fkColumn.name})\n`;
        sql += `  REFERENCES ${refTable.name}(${refColumn.name})`;
        sql += `\n  ON DELETE CASCADE`;
        sql += `;\n\n`;
      }
    }

    // Create indexes
    sql += `-- Indexes\n`;
    for (const table of tables) {
      const uniqueColumns = (table.erd_columns || []).filter(
        (c: any) => c.is_unique && !c.is_primary
      );

      for (const col of uniqueColumns) {
        sql += `CREATE UNIQUE INDEX idx_${table.name}_${col.name} ON ${table.name}(${col.name});\n`;
      }
    }

    return { sql };
  });
